language: ruby

addons:
  apt:
    sources:
      - git-core
    packages:
      - libmailtools-perl
      - git-email

script:
  - make test

rvm:
  - ruby-head
  - 3.0
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
