language: ruby

addons:
  apt:
    sources:
      - git-core
    packages:
      - libmailtools-perl
      - git-email

script:
  - make test

rvm:
  - ruby-head
  - 3.0.0
  - 2.7.0
  - 2.6.0
  - 2.5.0
  - 2.4.0
  - 2.3.0
  - 2.2.0
  - 2.1.0
  - 2.0.0
